name: Publish Docker
on: [push]
jobs:
  build:
    needs: init
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} letsencrypt-add-on
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Check add-on
        id: check
        run: |
          if [[ "${{ steps.info.outputs.architectures }}" =~ ${{ matrix.arch }} ]]; then
             echo "::set-output name=build_arch::true";
           else
             echo "${{ matrix.arch }} is not a valid arch for letsencrypt, skipping build";
          fi
      - name: Set build arguments
        if: steps.check.outputs.build_arch == 'true'
        run: |
          if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
              echo "BUILD_ARGS=--docker-hub-check" >> $GITHUB_ENV;
          fi
      - name: Login to DockerHub
        if: env.BUILD_ARGS == '--docker-hub-check'
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build letsencrypt add-on
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder@2022.01.0
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data \
            --addon
